use sha2::{Digest, Sha256};
use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
    process::Command,
};

struct Scratch(PathBuf);

impl Scratch {
    fn new() -> Self {
        let path = std::env::temp_dir().join(format!(
            "pangopup-regression-regenerate-{}",
            std::process::id()
        ));
        fs::create_dir(&path).expect("unique regeneration scratch");
        Self(path)
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn files(root: &Path, prefix: &Path, output: &mut BTreeSet<PathBuf>) {
    for entry in fs::read_dir(root).expect("fixture directory") {
        let entry = entry.expect("fixture entry");
        let path = entry.path();
        let relative = prefix.join(entry.file_name());
        if path.is_dir() {
            files(&path, &relative, output);
        } else {
            output.insert(relative);
        }
    }
}

#[test]
fn checked_regression_fixture_regenerates_byte_exactly() {
    let repository = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let checked = repository.join("tests/fixtures/snv-regression");
    let scratch = Scratch::new();
    let generated = scratch.0.join("generated");
    let output = Command::new(env!("CARGO_BIN_EXE_pangopup-regression-fixture"))
        .arg(repository.join("tests/fixtures/pangolin-precompute"))
        .arg(&generated)
        .output()
        .expect("run fixture generator");
    assert!(
        output.status.success(),
        "generator failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let mut checked_files = BTreeSet::new();
    let mut generated_files = BTreeSet::new();
    files(&checked, Path::new(""), &mut checked_files);
    files(&generated, Path::new(""), &mut generated_files);
    assert_eq!(generated_files, checked_files);
    let manifest_path = Path::new("bundle/manifest.json");
    let generated_manifest = fs::read(generated.join(manifest_path)).expect("generated manifest");
    let checked_manifest = fs::read(checked.join(manifest_path)).expect("checked manifest");
    let generated_id = format!("sha256:{:x}", Sha256::digest(&generated_manifest));
    let checked_id = format!("sha256:{:x}", Sha256::digest(&checked_manifest));
    for relative in checked_files {
        let mut actual = fs::read(generated.join(&relative)).expect("generated bytes");
        if relative == manifest_path {
            let mut value: serde_json::Value =
                serde_json::from_slice(&actual).expect("generated manifest JSON");
            assert_eq!(value["builder"]["version"], env!("CARGO_PKG_VERSION"));
            value["builder"]["version"] = serde_json::Value::String("0.1.0".to_owned());
            actual = serde_jcs::to_vec(&value).expect("historically rebound manifest");
        } else if actual
            .windows(generated_id.len())
            .any(|window| window == generated_id.as_bytes())
        {
            actual = String::from_utf8(actual)
                .expect("bundle identities occur only in UTF-8 fixture members")
                .replace(&generated_id, &checked_id)
                .into_bytes();
        }
        assert_eq!(
            actual,
            fs::read(checked.join(&relative)).expect("checked bytes"),
            "fixture byte drift: {}",
            relative.display()
        );
    }
}
