use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
    process::Command,
};

struct Scratch(PathBuf);

impl Scratch {
    fn new() -> Self {
        let path = std::env::temp_dir().join(format!(
            "pangopup-regression-regenerate-{}",
            std::process::id()
        ));
        fs::create_dir(&path).expect("unique regeneration scratch");
        Self(path)
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn files(root: &Path, prefix: &Path, output: &mut BTreeSet<PathBuf>) {
    for entry in fs::read_dir(root).expect("fixture directory") {
        let entry = entry.expect("fixture entry");
        let path = entry.path();
        let relative = prefix.join(entry.file_name());
        if path.is_dir() {
            files(&path, &relative, output);
        } else {
            output.insert(relative);
        }
    }
}

#[test]
fn checked_regression_fixture_regenerates_byte_exactly() {
    let repository = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let checked = repository.join("tests/fixtures/snv-regression");
    let scratch = Scratch::new();
    let generated = scratch.0.join("generated");
    let output = Command::new(env!("CARGO_BIN_EXE_pangopup-regression-fixture"))
        .arg(repository.join("tests/fixtures/pangolin-precompute"))
        .arg(&generated)
        .output()
        .expect("run fixture generator");
    assert!(
        output.status.success(),
        "generator failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let mut checked_files = BTreeSet::new();
    let mut generated_files = BTreeSet::new();
    files(&checked, Path::new(""), &mut checked_files);
    files(&generated, Path::new(""), &mut generated_files);
    assert_eq!(generated_files, checked_files);
    for relative in checked_files {
        assert_eq!(
            fs::read(generated.join(&relative)).expect("generated bytes"),
            fs::read(checked.join(&relative)).expect("checked bytes"),
            "fixture byte drift: {}",
            relative.display()
        );
    }
}
